### ISSUE TITLE
"- I" source search path

### ISSUE THREAD

**Issue by hitchpy** [NCAR/KGen#47]
Hello, I am trying to use KGen to extract kernels for CLM models within CESM. And the call has several module file dependencies, located at different subfolders. When I try to run the kgen script as follows, seems like the script wasn't using the path specified in -I to find module files? Any help would be appreciated. 

` ./kgen -i include.ini -I /lustre/atlas1/cli115/proj-shared/peiy/ACME/components/clm/src/  --invocation 1:2:3 --kernel-compile FC=ftn,FC_FLAGS='-O0' CNEcosystemDynMod.F90

Pre-processing is done
Reading CNEcosystemDynMod.F90
ERROR: Module, cnallocationmod, is not found at /autofs/nccs-svm1_home1/peiy/KGen/bin/CNEcosystemDynMod.F90. Please check include paths for searching module files.
`

**Comment by grnydawn** [comment]
Hello Yu,

I am glad to know that you are trying KGEN. CESM is one of complicated
model and KGEN needs macro definitions and include paths for, in principle,
all files used in kgen analysis. To make it simple to collect those
information, a Python script is created to generate those information
automatically from CESM log files. I put general steps to extract a kernel
from CESM below.
1. cloning KGEN from github( Strongly recommend to use the latest KGEN in
   "devel" branch )
   
   > > git clone https://github.com/NCAR/KGen.git
   > > git checkout devel
2. Generate include.ini
   
   > > $KGEN/bin/gen_include_cesm.py <path to your cesm log file>
   > > NOTE: You may need to collect information from multiple CESM log files such
   > > as from CLM and shared directory. In that case, try to repeat above command
   > > for each log files and merge "include.ini" files generated into one
   > > "include.ini" manually.
   > > NOTE :You can find those log files under "bld" directory created during
   > > CESM build.
3. Run the latest KGEN(on devel branch)
   
   > > $KGEN/kgen \
   > > -I include .ini \ # this is the include.ini file generated from using
   > > gen_include_cesm.py
   > > --invocation 0:0:1,0:0:2,0:0:3 \ # this is new syntax
   > > (mpi_rank:openmp_num:invocation) explained below in detail
   > > --mpi enable \ # "enable" should be used for MPI application
   > > --openmp enable \ # "enable" should be used for OpenMP application
   > > --kernel-compile FC=ftn,FC_FLAGS="-O0" \
   > > CNEcosystemDynMod.F90 # As there is no callsite is specified, I assume
   > > that KGEN directive is used instead in this source file.
   > > NOTE: new invocation syntax:
   > > syntax: mpi_rank:openmp_num:invocation
   > > examples
   > > 0:1:2  => mpi rank0, openmp num 1, and third invocation of the
   > > kernel(starts from 0)
   > > 1-2:3-4:5-6 => mpi rank1 and 2, openmp num 3 and 4, and sixth and
   > > seventh invocations of the kernel
   > > Use 0 for "non MPI application" and use 0 for "non OpenMP application" in
   > > the first and second part of the syntax.
4. Generate state data
   
   > > cp state/\* $CESMCASE/SourceMods/src.clm
   > > NOTE: Once previous kernel generation step is successful, "state" folder
   > > will be created. Copy the files in the folder to appropriate CESM
   > > "SourceMods" folder, I guess it is "src.clm" as you are interested in land
   > > model.
   > > $CESMCASE.submit
5. Run kernel
   
   > > cd kernel
   > > make
   > > NOTE: The KGEN generated kernel requires state date files generated from
   > > previous state generation step.

Please feel free to contact me if you have an issue on this kernel
generation.

Thanks,

## Youngsung Kim

Software Engineer, NCAR https://ncar.ucar.edu/
+1-303-497-2469

## youngsun@ucar.edu

On Fri, Apr 22, 2016 at 10:48 AM, yu pei notifications@github.com wrote:

> Hello, I am trying to use KGen to extract kernels for CLM models within
> CESM. And the call has several module file dependencies, located at
> different subfolders. When I try to run the kgen script as follows, seems
> like the script wasn't using the path specified in -I to find module files?
> Any help would be appreciated.
> 
> ` ./kgen -i include.ini -I
> /lustre/atlas1/cli115/proj-shared/peiy/ACME/components/clm/src/
> --invocation 1:2:3 --kernel-compile FC=ftn,FC_FLAGS='-O0'
> CNEcosystemDynMod.F90
> 
> Pre-processing is done
> Reading CNEcosystemDynMod.F90
> ERROR: Module, cnallocationmod, is not found at
> /autofs/nccs-svm1_home1/peiy/KGen/bin/CNEcosystemDynMod.F90. Please check
> include paths for searching module files.
> `
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/NCAR/KGen/issues/47

## 

Youngsung Kim

**Comment by hitchpy** [comment]
Thanks Youngsung for the instruction, I will test the devel branch. I did use the gen_include_cesm.py to generate ini file, but I only used the CESM build log, not CLM log, I will try that. ( Yes, I putted !$kgen callsite directive in the source file)

I saw that there are some significant rearrangement for the script. One question: **-I** now is for ini file? Then how can I specify the source code directory to search for dependent module files. I don't think the build log can provide dependency information alone. 

Again, thanks for your support, we are actively trying to test KGen with CLM modules. 

Yu

**Comment by grnydawn** [comment]
KGEN on "devel" branch is quite different from one on "master" branch now.
I am still making a considerable updates on devel branch but I thought it
is still worthy for you try now. And "-I" was my typo. "-i" is correct one.

Thanks,

On Fri, Apr 22, 2016 at 2:24 PM, Yu Pei notifications@github.com wrote:

> Thanks Youngsung for the instruction, I will test the devel branch. I did
> use the gen_include_cesm.py to generate ini file, but I only used the CESM
> build log, not CLM log, I will try that. ( Yes, I putted !$kgen callsite
> directive in the source file)
> 
> I saw that there are some significant rearrangement for the script. One
> question: _-I_ now is for ini file? Then how can I specify the source
> code directory to search for dependent module files. I don't think the
> build log can provide dependency information alone.
> 
> Again, thanks for your support, we are actively trying to test KGen with
> CLM modules.
> 
> Yu
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/NCAR/KGen/issues/47#issuecomment-213576910

## 

Youngsung Kim
