### ISSUE TITLE
--kernel-compile not modifying Makefile in example/simple

### ISSUE THREAD

**Issue by hitchpy** [NCAR/KGen#48]
Hello Youngsum,

I tried the simple example in devel branch with the new invocation syntax. I was able to run the example successfully, but seems like KGen isn't modifying the compiler settings based on the provided --kernel-compile flag? It uses Intel compiler regardless at the moment. Is that correct?

Thanks,
Yu

**Comment by grnydawn** [comment]
Hi Yu,

--kernel-compile flag is supposed to work in most of KGEN versions. Please
make sure that all arguments to the flag are specified without any blank
space between them.

By the way, the github sends me your message to my private email account,
which I am not frequently checking. It would be more convenient if you send
your email related KGEN to kgen@ucar.edu or youngsun@ucar.edu

Thanks,

On Mon, Apr 25, 2016 at 10:41 AM, Yu Pei notifications@github.com wrote:

> Closed #48 https://github.com/NCAR/KGen/issues/48.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/NCAR/KGen/issues/48#event-640287732

## 

Youngsung Kim
