### ISSUE TITLE
procedure stmt is remained even though the procedure is not used

### ISSUE THREAD

**Issue by grnydawn** [NCAR/KGen#52]
I am trying to understand what you meant by "init" functions. From looking at the source file, I found

!     procedure, public  :: Init  
!     procedure, public  :: Restart  
!     procedure, public  :: CropRestIncYear
!     procedure, private :: InitAllocate
!     procedure, private :: InitHistory  
!     procedure, private :: InitCold 

Are they "init" functions?

If so, I guess that KGen figured out that those functions are not required to run the kernel part. However, if those procedure statement remained even though they are not used within the kernel region, that is a KGen bug. KGen should remove the procedure statement lines too.

**Comment by hitchpy** [comment]
Hello Youngsung,

Seems like based on Cindy's example, you decided to keep the procedures in the derived type, instead  of deleting them? I tried to rerun the latest version KGen on my previous example, but this time I run into issues with not deleted procedures. Specifically, as shown in above, there's a procedure called Restart, it employs PIO library for restart file output. KGen is trying to analyze pio, but that is a whole separated code base and I want to exclude that.

So my question is, how to specify the exclude.ini file to exclude certain use clauses? Thank you very much.

Yu

**Comment by grnydawn** [comment]
commit 3f8e91fb7bc5e4b20729a840ca63866f4063b7de on devel branch resolved this issue.
